server:
  port: 9192

spring:
  application:
    name: ORDER-SERVICE

  config:
    import: optional:configserver:http://localhost:9196

  datasource:
    url: jdbc:postgresql://localhost:5432/bedrock-db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] --- [%15.15t] %-40.40logger{39} : %m%n"

  file:
    path: D:/Gopal/Projects/api-gateway-microservices-design-pattern/logs/microservice

  level:
    root: INFO
    com.gp: DEBUG
    com.gp.order_service.client: DEBUG
    feign: DEBUG
    org.hibernate.SQL: DEBUG

management:
  health:
    show-components: always
    show-details: always
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always


  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5

resilience4j:
  circuitbreaker:
    instances:
      paymentServiceCB:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      paymentServiceRetry:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
  ratelimiter:
    instances:
      paymentServiceRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 0
        register-health-indicator: true
  timelimiter:
    instances:
      paymentServiceCB:
        timeout-duration: 5s